version: "3.9"

services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"

  question-service:
    build: ./question-service
    ports:
      - "8001:8001"

  quiz-service:
    build: ./quiz-service
    ports:
      - "8002:8002"
    depends_on:
      - question-service
      - result-service
      - redis

  result-service:
    build: ./result-service
    ports:
      - "8003:8003"

  ai-service:
    build: ./ai-service
    ports:
      - "8004:8004"
    depends_on:
      - result-service
      - redis

  api-gateway:
    build: ./api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - auth-service
      - question-service
      - quiz-service
      - result-service
      - ai-service